### ISSUE TITLE
Errors 

### ISSUE THREAD

**Issue by LeamHall** [wildfire142/Fire-Fusion-and-Steel#6]
Python 3.6.5 on CentOS 6 

I noticed that you spell "Length" sometimes and "Lenght" often. Might be related.

####
```python
 /usr/local/bin/python3 Fire\ Fusion\ and\ Steel.py 
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/tkinter/__init__.py", line 1702, in __call__
    return self.func(*args)
  File "/home/leam/lang/git/others/Fire-Fusion-and-Steel/Gauss_Frame.py", line 122, in <lambda>
    self.GaussAmmoDiameter.bind ('<KeyRelease>', lambda event: Set_Outputs() )
  File "/home/leam/lang/git/others/Fire-Fusion-and-Steel/Gauss_Frame.py", line 536, in Set_Outputs
    Gauss_Weapons.AmmoDiameter = self.AmmoDiameter.get()
  File "/usr/local/lib/python3.6/tkinter/__init__.py", line 526, in get
    return self._tk.getdouble(self._tk.globalgetvar(self._name))
_tkinter.TclError: expected floating-point number but got ""
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/tkinter/__init__.py", line 1702, in __call__
    return self.func(*args)
  File "/home/leam/lang/git/others/Fire-Fusion-and-Steel/Gauss_Frame.py", line 122, in <lambda>
    self.GaussAmmoDiameter.bind ('<KeyRelease>', lambda event: Set_Outputs() )
  File "/home/leam/lang/git/others/Fire-Fusion-and-Steel/Gauss_Frame.py", line 536, in Set_Outputs
    Gauss_Weapons.AmmoDiameter = self.AmmoDiameter.get()
  File "/usr/local/lib/python3.6/tkinter/__init__.py", line 526, in get
    return self._tk.getdouble(self._tk.globalgetvar(self._name))
_tkinter.TclError: expected floating-point number but got ""
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/tkinter/__init__.py", line 1702, in __call__
    return self.func(*args)
  File "/home/leam/lang/git/others/Fire-Fusion-and-Steel/Gauss_Frame.py", line 122, in <lambda>
    self.GaussAmmoDiameter.bind ('<KeyRelease>', lambda event: Set_Outputs() )
  File "/home/leam/lang/git/others/Fire-Fusion-and-Steel/Gauss_Frame.py", line 536, in Set_Outputs
    Gauss_Weapons.AmmoDiameter = self.AmmoDiameter.get()
  File "/usr/local/lib/python3.6/tkinter/__init__.py", line 526, in get
    return self._tk.getdouble(self._tk.globalgetvar(self._name))
_tkinter.TclError: expected floating-point number but got ""
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/tkinter/__init__.py", line 1702, in __call__
    return self.func(*args)
  File "/home/leam/lang/git/others/Fire-Fusion-and-Steel/Small_Arms_Frame.py", line 166, in <lambda>
    self.SmallArmsAmmoDiameter.bind ('<KeyRelease>', lambda event: Set_Outputs() )
  File "/home/leam/lang/git/others/Fire-Fusion-and-Steel/Small_Arms_Frame.py", line 1106, in Set_Outputs
    Small_Arms.AmmoDiameter = self.AmmoDiameter.get()
  File "/usr/local/lib/python3.6/tkinter/__init__.py", line 526, in get
    return self._tk.getdouble(self._tk.globalgetvar(self._name))
_tkinter.TclError: expected floating-point number but got ""
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/tkinter/__init__.py", line 1702, in __call__
    return self.func(*args)
  File "/home/leam/lang/git/others/Fire-Fusion-and-Steel/Small_Arms_Frame.py", line 173, in <lambda>
    self.SmallArmsCartridgeLenght.bind ('<KeyRelease>', lambda event: Set_Outputs() )
  File "/home/leam/lang/git/others/Fire-Fusion-and-Steel/Small_Arms_Frame.py", line 1107, in Set_Outputs
    Small_Arms.CartridgeLenght = self.CartridgeLenght.get()
  File "/usr/local/lib/python3.6/tkinter/__init__.py", line 526, in get
    return self._tk.getdouble(self._tk.globalgetvar(self._name))
_tkinter.TclError: expected floating-point number but got ""
```

**Comment by wildfire142** [comment]
The spelling issue is my dyslexia kicking in and the error is when a entry box is empty as a later call expects a value but is empty will look how to get round that a some point.

**Comment by LeamHall** [comment]
You have some good defaults. And really, for less than a couple years of Python this is very nice!

**Comment by wildfire142** [comment]
I think I've sorted it entry boxes now only update when they have something in them every much a kludge but it works. also squashed a couple of other bugs, thanks for spotting and highlighting this.
